# Generated by Django 4.2.11 on 2024-07-10 05:29

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.contrib.routable_page.models
import wagtail.fields
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0093_uploadedfile"),
        ("products", "0012_auto_20240701_0307"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            (
                                "search",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "title",
                                            wagtail.blocks.CharBlock(
                                                max_length=255, required=True
                                            ),
                                        ),
                                        (
                                            "placeholder",
                                            wagtail.blocks.CharBlock(
                                                max_length=255, required=True
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "cta",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "text",
                                            wagtail.blocks.CharBlock(
                                                max_length=255, required=True
                                            ),
                                        ),
                                        ("link", wagtail.blocks.URLBlock(required=True)),
                                        (
                                            "type",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[
                                                    ("Community", "Community"),
                                                    ("Paid", "Paid"),
                                                    ("Other", "Other"),
                                                ]
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            ("featured_articles", wagtail.blocks.StructBlock([])),
                            (
                                "product_snippet",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "product",
                                            wagtail.snippets.blocks.SnippetChooserBlock(
                                                required=True, target_model="products.Product"
                                            ),
                                        )
                                    ]
                                ),
                            ),
                        ]
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Index",
                "verbose_name_plural": "Product Indexes",
            },
            bases=(wagtail.contrib.routable_page.models.RoutablePageMixin, "wagtailcore.page"),
        ),
        migrations.CreateModel(
            name="StructuralPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
